name: nest-action
run-name: ${{ github.actor }}
on: [push]
jobs:
    integration:
        runs-on: ubuntu-latest
        steps:
            - name: integration
              run: |
                echo "Integration"

    dev-source-map-upload:
        runs-on: ubuntu-latest
        if: github.ref_name == 'develop'
        environment: dev
        needs: integration
        steps:
            # - uses: actions/checkout@v4
            # - uses: actions/setup-node@v4
            #   with:
            #     node-version: 18
            - name: output branch test
              run: echo ${{secrets.BRANCH}}
            - name: url 環境
              run: echo ${{vars.API_URL}}
                
            