name: nest-action
run-name: ${{ github.actor }}
on: [push]
jobs:
    integration:
        runs-on: ubuntu-latest
        steps:
            - name: integration
              uses: actions/checkout@v4

    dev-source-map-upload:
        runs-on: ubuntu-latest
        if: github.ref_name == 'develop'
        environment: dev
        needs: integration
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Run
              run: |
                npm install
                npm run build
                npm run sentry:sourcemaps
              env:
                SENTRY_DSN: ${{ secrets.SENTRY_DSN}}
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            - name: finish
              run: echo ${{secrets.SENTRY_AUTH_TOKEN}}
    staging-source-map-upload:
        runs-on: ubuntu-latest
        if: github.ref_name == 'main'
        environment: prod
        needs: integration
        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: 18
    prod-source-map-upload:
        # uses: toasahi/nest-sentry/.github/workflows/prod-workflow.yml@main
        runs-on: ubuntu-latest
        if: github.ref_name == 'main'
        environment: prod
        needs: integration
        steps:
            - uses: actions/setup-node@v4
              with:
                node-version: 18
                
            